---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: app855
    run_list:
      - recipe[peopletools_test::app855]
    attributes:
      peopletools:
        archive_repo: <%= ENV['PT_855_ARCHIVE_REPO'] %>
        db_host: 'localhost'
        db_name: 'KITCHEN'
        ps_app_home:
          archive_repo: <%= ENV['PS_APP_HOME_ARCHIVE_REPO'] %>
  - name: app856
    run_list:
      - recipe[peopletools_test::app856]
    attributes:
      peopletools:
        archive_repo: <%= ENV['PT_856_ARCHIVE_REPO'] %>
        db_host: 'localhost'
        db_name: 'KITCHEN'
        ps_app_home:
          archive_repo: <%= ENV['PS_APP_HOME_ARCHIVE_REPO'] %>
  - name: prcs855
    run_list:
      - recipe[peopletools_test::prcs855]
    attributes:
      peopletools:
        archive_repo: <%= ENV['PT_855_ARCHIVE_REPO'] %>
        db_host: 'localhost'
        db_name: 'KITCHEN'
        ps_app_home:
          archive_repo: <%= ENV['PS_APP_HOME_ARCHIVE_REPO'] %>
  - name: prcs856
    run_list:
      - recipe[peopletools_test::prcs856]
    attributes:
      peopletools:
        archive_repo: <%= ENV['PT_856_ARCHIVE_REPO'] %>
        db_host: 'localhost'
        db_name: 'KITCHEN'
        ps_app_home:
          archive_repo: <%= ENV['PS_APP_HOME_ARCHIVE_REPO'] %>
  - name: web855
    run_list:
      - recipe[peopletools_test::web855]
    attributes:
      peopletools:
        archive_repo: <%= ENV['PT_855_ARCHIVE_REPO'] %>
        ps_app_home:
          archive_repo: <%= ENV['PS_APP_HOME_ARCHIVE_REPO'] %>
  - name: web856
    run_list:
      - recipe[peopletools_test::web856]
    attributes:
      peopletools:
        archive_repo: <%= ENV['PT_856_ARCHIVE_REPO'] %>
        ps_app_home:
          archive_repo: <%= ENV['PS_APP_HOME_ARCHIVE_REPO'] %>
