---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.7

suites:
  - name: app
    run_list:
      - recipe[peopletools::app]
    attributes:
      peopletools:
        archive_repo: <%= ENV['PEOPLETOOLS_ARCHIVE_REPO'] %>
  - name: web
    run_list:
      - recipe[peopletools::web]
    attributes:
      peopletools:
        archive_repo: <%= ENV['PEOPLETOOLS_ARCHIVE_REPO'] %>
