---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: app
    run_list:
      - recipe[peopletools::app]
    attributes:
      peopletools:
        archive_repo: <%= ENV['PEOPLETOOLS_ARCHIVE_REPO'] %>
        db_host: localhost
        db_name: KITCHEN
        ps_app_home:
          archive_repo: <%= ENV['PEOPLETOOLS_PS_APP_HOME_ARCHIVE_REPO'] %>
  - name: web
    run_list:
      - recipe[peopletools::web]
    attributes:
      peopletools:
        archive_repo: <%= ENV['PEOPLETOOLS_ARCHIVE_REPO'] %>
        ps_app_home:
          archive_repo: <%= ENV['PEOPLETOOLS_PS_APP_HOME_ARCHIVE_REPO'] %>
