name 'peopletools_test'
maintainer 'University of Derby'
maintainer_email 'serverteam@derby.ac.uk'
license 'Apache 2.0'
description 'This cookbook is used to test peopletools resources'
version '0.1.0'
source_url 'https://github.com/universityofderby/chef-peopletools/test/cookbooks/peopletools_test'
issues_url 'https://github.com/universityofderby/chef-peopletools/issues'

depends 'limits', '~> 1.0'
depends 'peopletools'
depends 'sysctl', '~> 0.8'
